### ISSUE TITLE
Library Problems with IMU and Wire.h ??

### ISSUE THREAD

**Issue by art1** [art1/UE22-Balloon-Project-Software#2]
balloon_main can't be compiled when using IMU and the other sensors. Might be local problem with duplicate libraries. To check.

**Comment by petket-5** [comment]
What is the compile error message? I had similar problems when using the 1.0 version of the IDE instead of the 1.8.0. Furthermore, the libraries to be used are included in the project file.

**Comment by art1** [comment]
`Arduino: 1.8.1 (Mac OS X), Board: "Arduino Mega ADK"

/var/folders/lc/z8hjlc4s08v7hffxvs81l_v40000gn/T//ccjU2VI0.ltrans0.ltrans.o: In function `__vector_39':
/private/var/folders/lc/z8hjlc4s08v7hffxvs81l_v40000gn/T/AppTranslocation/69BD6603-8929-4BDC-ABC5-461EF161E462/d/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/src/utility/twi.c:536: undefined reference to `IMU::IMU()'
/private/var/folders/lc/z8hjlc4s08v7hffxvs81l_v40000gn/T/AppTranslocation/69BD6603-8929-4BDC-ABC5-461EF161E462/d/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire/src/utility/twi.c:536: undefined reference to `IMU::IMU()'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Mega ADK.
`

**Comment by art1** [comment]
problem solved. Bug in default constructor
